routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('tasks', 'TasksController');
Route::any('/archive','TasksController@archive')->name('archive');
Route::any('/archive/destroy/{id}','TasksController@destroya')->name('task.destroy');
Route::any('/archive/store/{id}','TasksController@storearchive')->name('storearchive');
Route::any('/archive/unstore/{id}','TasksController@unarchive')->name('unarchive');
Route::auth();
Route::get('/got', [
    'middleware' => ['auth'],
    'uses' => function () {
     echo "You are allowed to view this page!";
  }]);

;

Route::get('/', function () {
    return view('/tasks');
});





Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/archive.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Task's Archive</h1>
<table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nametask</td>
          <td>Description</td>
	  <td>Type</td>
          <td colspan = 3>Actions</td>
        </tr>
    </thead>
	<div>
   	 	<a style="margin: 50px;" href="{{ route('tasks.index')}}" class="btn btn-primary">Tasks</a>
    	</div> 
 
	 @foreach($tasks as $task)
   @if($task->archive === false)
        <tr> 
            <td>{{$task->id}}</td>
            <td>{{$task->nametask}}</td>
	    <td>{{$task->descri}}</td>
	    <td>{{$task->archive}}</td>

	    <td>
		@php
		$tipo =	$task->tipo_id;
		
		$tipos = DB::table('tipos')
		->where('id',$tipo)	
		->first();
			
		echo $tipos->namet;
		@endphp
		
	    </td>
		<td>
                <a href="{{ route('tasks.edit',$task->id)}}" class="btn btn-primary">Edit</a>
            </td>
		<td>
               <form action="{{ route('task.destroy', $task->id)}}" method="post">
                  @csrf
		  @method('DELETE')
                  <button class="btn btn-danger" action="submit">Delete</button>
            <td>
	<a href="{{ route('unarchive', $task->id)}}" class="btn btn-primary"	value="$task->id">Remove from Archive</a>
            </td> 
                </form>
            </td>
	<br />
	@endif
     	</tr>
  	</div>
	@endforeach
</div>
</div>
@endsection

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Laravel 5.8 & MySQL CRUD Tutorial</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    @yield('main')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/new.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel' Servio</title>
	
	
	
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
	<?php
	try {$dbuser = 'postgres';
	$dbpass = 'ciao123';
	$dbhost = '127.0.0.1';
	$dbname='mydb';
	$connec = new PDO("mysql:host=$dbhost;dbname=$dbname", $dbuser, $dbpass);
	}catch (PDOException $e) {
	echo "Error : " . $e->getMessage() . "<br/>";
	die();
	}
	?>
        <div class="flex-center position-ref full-height">
            

            <div class="content">
                <div class="title m-b-md">
                    Todoapp
                </div>
		<?php
	$sql = 'SELECT idtask, nometask, date, descr FROM Tasks ORDER BY date';
	foreach ($connec->query($sql) as $row) 
	{
	print $row['idtask'] . " ";
	print $row['nometask'] . "-->";
	print $row['descr'] . "-->";
	print $row['date'] . "<br>";
	}
	?>
                
            </div>
        </div>
    </body>
</html>