routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('tasks', 'TasksController');
Route::any('/archive','TasksController@archive')->name('archive');
Route::any('/archive/destroy/{id}','TasksController@destroya')->name('task.destroy');
Route::any('/archive/store/{id}','TasksController@storearchive')->name('storearchive');
Route::any('/archive/unstore/{id}','TasksController@unarchive')->name('unarchive');
Route::auth();
Route::get('/got', [
    'middleware' => ['auth'],
    'uses' => function () {
     echo "You are allowed to view this page!";
  }]);

;

Route::get('/', function () {
    return view('/tasks');
});





Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
}

app/Tasks.php
<?php

namespace App;
use App\Tipo;
use App\Status;

use Illuminate\Database\Eloquent\Model;

class Tasks extends Model
{
     protected $fillable = [
        'nametask',
        'descri',
	    'date',
        'archive',
        'status',
        'completiondate'
];
}
public function tipo()
    {
        return $this->hasOne(Tipo.class);
    }
public function status()
    {
        return $this->hasOne(Status.class);
    }
}

app/Http/Controllers/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
}

app/Http/Controllers/Tasks.php
<?php

namespace App\Http\Controllers;

use Illuminate\Database\Eloquent\Model;

class Tasks extends Model
{
     protected $fillable = [
        'nametask',
        'descri',
	'date',
        'archive',
        'status',
        'completiondate',
        'priority'
];
}

app/Http/Controllers/TasksController.php
<?php
use App\Tasks;
use App\Tipo;
namespace App\Http\Controllers;
use DB;
use Illuminate\Http\Request;
use App\Status;
use App\User;
use App\priority;
use Log;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        Log::info("here");
        Log::info($request);
       

       $tasks = Tasks::all()->where('archive',true)
                            ->sortBy('priority');
       $statuses = Status::all();
        $types = Tipo::all();
        $priorities = priority::all();
        

        return view('tasks.index', compact('tasks','statuses','types','priorities'));
   
    }
    public function dropindex(Request $request)
    {
        
       
        return view('tasks.index', compact('tasks','statuses','type',));

    }

	public function storearchive(Request $request,$id)
    {
	Log::info($request);
	       
	$task = Tasks::find($id);
	//$task->save();
	$task = DB::table('tasks')
	->where('id', $id)
	->update(['archive'=> 0]);
        return redirect('/archive')->with('success', 'task updated!');

   
 }
 public function unarchive(Request $request,$id)
 {
 Log::info($request);
        
 $task = Tasks::find($id);
 //$task->save();
 $task = DB::table('tasks')
 ->where('id', $id)
 ->update(['archive'=> 1]);
     return redirect('/tasks')->with('success', 'task updated!');


}
    
	public function archive()
    {
       $tasks = Tasks::all();
         $type = Tipo::all();
        $statuses = Status::all();
        $ciao = Status::all();
        return view('/archive',compact('tasks','ciao'));
   
 }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
	

    public function create()
    {
	
    $type = Tipo::all();
    $statuses = Status::all();
    $priorities = priority::all();
        return view('tasks.create',compact('type','statuses','priorities'));
	
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
	Log::info($request);
        $request->validate([
            'nametask'=>'required',
            'descri'=>'required',
        'type_id' =>'required',
        'status' =>'required',
        'completiondate' =>'required',
        'priority'  => 'required'
        ]);

        $task = new Tasks([
            'nametask' => $request->get('nametask'),
            'descri' => $request->get('descri'),
            'completiondate' => $request->get('completiondate'),
            
        ]);

    $task->tipo_id = $request->get('type_id');
    $task->status = $request->get('status');
    $task->priority = $request->get('priority');
	Log::info($task);
	$task->archive =(1);
        $task->save();
        return redirect('/tasks')->with('success', 'Task saved!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    { 
        $task = Tasks::find($id);
        $type = Tipo::all();
        $statuses = Status::all();
        $priorities = priority::all();
        return view('tasks.show',compact('task','type','statuses','priorities'));
     }
 

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
   public function edit($id)
    	{
        $task = Tasks::find($id);
        $type = Tipo::all();
        $statuses = Status::all();
        $priorities = priority::all();
        return view('tasks.edit',compact('task','type','statuses','priorities'));        
   
   	 }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nametask'=>'required',
            'descri'=>'required',
            'type_id' =>'required',
            'status' =>'required',
            'completiondate' =>'required',
            'priority'  => 'required'
        ]);

        $task = Tasks::find($id);
        $task->nametask =  $request->get('nametask');
        $task->descri = $request->get('descri');
        $task->tipo_id = $request->get('type_id');
        $task->status = $request->get('status');
        $task->completiondate = $request->get('completiondate');
        $task->priority = $request->get('priority');
        
        $task->save();

        return redirect('/tasks')->with('success', 'task updated!');
  
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $task = Tasks::find($id);
        $task->delete();

        return redirect('/tasks')->with('success', 'Task deleted!');
   
    }
	public function destroya($id)
    {
       $task = Tasks::find($id);
        $task->delete();

        return redirect('/archive')->with('success', 'Task deleted!');
   
    }

}

resources/views/tasks/archive.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Are u sure to delete a task??</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('tasks.destroy'), $task->id }}">
          @csrf
	@method
         
          <button type="submit" class="btn btn-primary-outline">Delete task</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/tasks/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a task</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('tasks.store') }}">
          @csrf
          <div class="form-group">    
              <label for="nametask">Name Task:</label>
              <input type="text" class="form-control" name="nametask"/>
          </div>

          <div class="form-group">
              <label for="descri">Description:</label>
              <input type="text" class="form-control" name="descri"/>
          </div>
	
	 <div class="form-group">
  	<label for="type_id">Type:</label>
  	<select class="form-control" name="type_id">
	<option> </option>
    	@foreach ($type as $tipo)
	<option value="{{$tipo->id}}">
	{{$tipo->namet}}
	@endforeach	
	</option>
  	</select>
	</div> 
  <div class="form-group">
  	<label for="status">Status:</label>
  	<select class="form-control" name="status">
	<option> </option>
  @foreach($statuses as $status)
		  
		  <option value="{{$status->id}}"  > 
		  {{$status->status}}
			
		  
		  </option>
		  @endforeach
	</option>
  	</select>
  </div> 
  <div class="form-group">
  	<label for="priority">Priority:</label>
  	<select class="form-control" name="priority">
	<option> </option>
  @foreach($priorities as $priority)
		  
		  <option value="{{$priority->id}}"  > 
		  {{$priority->namep}}
			
		  
		  </option>
		  @endforeach
	</option>
  	</select>
	</div> 
    <div class="form-gruop">
    <label for="completiondate">Completion Date:</label>
    <input type="date" id="completiondate" name="completiondate"
            value="@php
            $date = new DateTime();
              echo $date->getTimestamp();
            @endphp" >
    </div>
          <button type="Add" class="btn btn-primary-outline">Add task</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/tasks/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a task</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('tasks.update', $task->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">
                <label for="priority">Priority:</label>
                <select class="form-control" name="priority">
                <option> @foreach($priorities as $priority)
											@if($priority->id === $task->priority)	
												 {{$priority->namep}}
											@endif
                                        @endforeach
                                    </option>
                    @foreach($priorities as $priority)
                    
                    <option value="{{$priority->id}}"  > 
                    {{$priority->namep}}
                        
                    
                    </option>
                    @endforeach
                </option>
                </select>
                </div> 

            <div class="form-group">

                <label for="nametask">nametask:</label>
                <input type="text" class="form-control" name="nametask" value={{ $task->nametask }} />
            </div>

            <div class="form-group">
                <label for="descri">descri:</label>
                <input type="text" class="form-control" name="descri" value={{ $task->descri }} />
            </div>
			<label for="type_id">Type:</label>
  		<select class="form-control" name="type_id">
			
		<option value="{{$task->tipo_id}}">
                                      @foreach($type as $types)
											@if($types->id === $task->tipo_id)	
												 {{$types->namet}}
											@endif
                                        @endforeach
				
		 </option>
    		@foreach ($type as $tipo)
		<option value="{{$tipo->id}}">
		{{$tipo->namet}}
		@endforeach	
		</option>
          </select>
          
          <div class="form-group">
  	<label for="status">Status:</label>
  	<select class="form-control" name="status">
	<option>                            @foreach($statuses as $status)
											@if($status->id === $task->status)	
												 {{$status->status}}
											@endif
                                        @endforeach
                                    </option>
            @foreach($statuses as $status)
		  
		  <option value="{{$status->id}}"  > 
		  {{$status->status}}
			
		  
		  </option>
		    @endforeach
	</option>
  	</select>
     </div> 
                    <div class="form-gruop">
                    <label for="completiondate">Completion Date:</label>
                    <input type="date" id="completiondate" name="completiondate"
                            value="{{ $task->completiondate }} ">
                    </div>
		<br></br>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/tasks/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Tasks</h1>    
  <table class="table table-striped">
    <thead>
	@if(Auth::check())
		<p>You are logged</p>
        <tr>
			<td>Priority</td>
            <td>ID</td>
            <td>Nametask</td>
            <td>Description</td>
	  		<td>Type</td>	
			<td>Status</td>
		    <td>Completion Date</td>
		
          <td colspan = 4 >Actions</td>
        </tr>
    </thead>
    <tbody>
	<div>
   	 	<a style="margin: 19px;" href="{{ route('tasks.create')}}" 				class="btn btn-primary">New Task</a>
  
   	 	<a style="margin: 25px;" href="{{ route('archive')}}" class="btn btn-primary">Archive</a>
			<!--			@php 
						$status = $statuses;
						@endphp
			<form href="{{ route('tasks.index')}}" method="get">
                   				
					<button class="btn btn-danger" action="submit" value="{{$status[1]->id}}">new</button>
					<input type="text" value="2" />
					
				      <select name="status">                      
                            <option value="null">All</option>
                            @foreach ($statuses as $status)
                                <option value="{{ $status->id }}" >{{$status->status}}</option>
                            @endforeach
                        </select>
						{{$status->id}}
						
            </form>-->

			
			<!--<div class="form-group">
  		<select class="btn btn-white" style="margin: 25px;" name="status"	href="{{ route('tasks.index')}}">
		  <option> </option>
		  @foreach($statuses as $status)
		  
		  <option value="{{$status->id}}"  > 
		  {{$status->status}}
			
		  
		  </option>
		  @endforeach
		  </select>
		{{$tasks}}
		{{$status->id}}
		
		</div>-->
		

	
		
    </div>  
  	
		</div>

	<div class="col-sm-12">
	
  		@if(session()->get('success'))
   	 		<div class="alert alert-success">
      				{{ session()->get('success') }}  
    			</div>
  		@endif
		 
        @foreach($tasks as $task)
			@php
				$date = date('Y-m-d');
				
				$color =['white','#5cd65c'];
				if($task->completiondate < $date)
						$hi = 1;
					else	
					 	$hi = 0;
						
			@endphp
					     
									<tr style='background-color:{{$color[$hi]}}'>
									<td>
									@foreach($priorities as $priority)
											@if($priority->id === $task->priority)	
												 {{$priority->namep}}
											@endif
										@endforeach
									</td>
									<td>{{$task->id}}</td>
									<td>{{$task->nametask}}</td>
									<td>{{$task->descri}}</td>
									<td>
										@foreach($types as $type)
											@if($type->id === $task->tipo_id)	
												 {{$type->namet}}
											@endif
										@endforeach
				
									</td>
									<td>
										@foreach($statuses as $status)
											@if($status->id === $task->status)	
												 {{$status->status}}
											@endif
										@endforeach
									
									</td>
									<td>{{$task->completiondate}}</td>

									<td>
										<a href="{{ route('tasks.show',$task->id)}}" class="btn btn-primary">Show</a>
									</td>

									<td>
										<a href="{{ route('tasks.edit',$task->id)}}" class="btn btn-primary">Edit</a>
									</td>
									<td>
										<form action="{{ route('tasks.destroy', $task->id)}}" method="post">
												@csrf
												@method('DELETE')
												<button class="btn btn-danger" action="submit">Delete
												</button>
										
										</form>
									<td>
										<a href="{{ route('storearchive', $task->id)}}" class="btn btn-primary"	value="$task->id">Store in Archive</a>
										</td>            
									
				
			
								</tr>
						
        @endforeach
		@endif
		@if(Auth::guest())
              <a href="/login" class="btn btn-info"> You need to login to see the Tasks's list >></a>
            @endif
	</tbody>
  </table>
<div>
</div>
@endsection

resources/views/tasks/show.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">View a Tasks</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form  action="{{ route('tasks.index')}}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

            <label for="nametask">Priority :  </label>
            <label for="nametask">
                                        @foreach($priorities as $priority)
											@if($priority->id === $task->priority)	
												 {{$priority->namep}}
											@endif
										@endforeach
            </label>

            </div>

            <div class="form-group">

                <label for="nametask">Name of task:  </label>
                <label for="nametask">{{ $task->nametask }}</label>
               
            </div>

            <div class="form-group">
                <label for="descri">Description :  </label>
                <label for="descri">{{ $task->descri }}</label>
                
            </div>

            <div class="form-group">
                <label for="tipo_id">Type :     </label>
                <label for="tipo_id">
                                        @foreach($type as $types)
											@if($types->id === $task->tipo_id)	
												 {{$types->namet}}
											@endif
                                        @endforeach
                </label>
                
            </div>
            <div class="form-group">
                <label for="status">Status :  </label>
                <label for="status">       
                                    @foreach($statuses as $status)
											@if($status->id === $task->status)	
												 {{$status->status}}
											@endif
										@endforeach
                           
                </label>
                
             </div>
             <div class="form-group">
                <label for="completiondate">Completion Date :  </label>
                <label for="completiondate">{{ $task->completiondate }}</label>

                    
		            <br></br>
            <button type="submit" class="btn btn-primary">Go back</button>
        </form>
    </div>
</div>
@endsection